server:
  port: 8081

spring:
  application:
    name: JobSearch

  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:./db/job_seeker;AUTO_SERVER=TRUE
    username: Kanybek
    password: Kanybek12345
    driver-class-name: org.h2.Driver

    hikari:
      maximum-pool-size: 5

  liquibase:
    change-log: classpath://db/changelog/master.yaml

  mvc:
    static-path-pattern: /static/**
  freemarker:

    expose-session-attributes: true
    expose-spring-macro-helpers: true

  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    username: zhanybek20065732@gmail.com
    password: xmqh zdnf kjld qdkh
    port: 587
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8081/login/oauth2/code/google.
            client-id: 67559407387-g1ocir2bbsqvtmaqiq3novpao34s35c5.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org:
      springframework:
        security: INFO
        web:
          servlet:
            DispatcherServlet: INFO


