server:
  port: 8081

spring:
  application:
    name: JobSearch
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:./db/job_seeker;AUTO_SERVER=TRUE
    username: Kanybek
    password: Kanybek12345
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath://db/changelog/master.yaml
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true
    expose-spring-macro-helpers: true

  sql:
    init:
      mode: always


logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          servlet:
            DispatcherServlet: DEBUG


