INSERT INTO categories (name)
VALUES
    ('Marketing'),
    ('Sales'),
    ('Design'),
    ('HR'),
    ('Finance'),
    ('Operations'),
    ('Customer Support'),
    ('Engineering'),
    ('Business Development'),
    ('Product Management'),
    ('Data Science'),
    ('Legal'),
    ('Project Management'),
    ('Quality Assurance'),
    ('Public Relations'),
    ('Research and Development'),
    ('Content Creation'),
    ('Administration'),
    ('Supply Chain'),
    ('Consulting'),
    ('Customer Success'),
    ('Creative Direction'),
    ('Event Management'),
    ('Real Estate'),
    ('Accounting'),
    ('Security'),
    ('Procurement'),
    ('User Experience'),
    ('Training');
